apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-actual
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-actual
    app.kubernetes.io/part-of: actual
  name: 1-actual
  namespace: shebert
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: 1-actual
status:
  loadBalancer: {}
